### ISSUE TITLE
Search and filtering (other than by ID)

### ISSUE THREAD

**Issue by kovinet** [Weble/ZohoCrmApi#102]
Is it possible to get a record by some field, like for example I would like to get Contact from ZOHO by Email or by Phone.  

Now I get DuplicateData exception when trying to insert new Contact which already exists with same Email but it is not clear how can I check first and get ID of the contact so I can do an update.

Another option would be `upsert` method (create or update if existing), is something like this supported by this package?

**Comment by Skullbock** [comment]
Hi, we were implementing it in the next version, not sure when we'll have the time to finish that, but you can try it:
https://github.com/Weble/ZohoCrmApi/pull/90/files

Basically try using the `dev-feature/api-v4` as the version for the zoho crm dependency in you composer json and you'll get that version with the support for external ids.
