### ISSUE TITLE
Relance on bentools/guzzle-throttle-middleware prevents installation in Laravel 8

### ISSUE THREAD

**Issue by tm1000** [Weble/ZohoCrmApi#68]
Back to guzzle 7 issues. The reliance on https://github.com/bentools/guzzle-throttle-middleware prevents updates to Laravel 8 because of the Guzzle 6 v 7 conflict. It looks like https://github.com/bentools/guzzle-throttle-middleware is abandoned. So while this library provides the ability to throttle it's outdated. 

Two suggestions:

1. Remove the need for any middleware. Since you allow passing a custom client anyways the user is able to add any throttling they need (This is my preferred option)
2. Use https://github.com/caseyamcl/guzzle_retry_middleware, this also has a throttle built in and I use it against several other APIs. It can also work directly against the 429 responses Zoho returns.

My company (with @xrobau) utilizes your work exclusively for Zoho Books and we are looking into moving to this CRM library as well (with service providers in Laravel) so trying to get this to work for our usages as well as yours :-)

**Comment by Skullbock** [comment]
Hi, as per the discussion on the zoho client repo, this is a good idea.
Maybe a new version with less dependencies and (super cool) a laravel service provider? Maybe compatible with socialite's zoho auth provider?

We'll draft a roadmap together if you wish
