### ISSUE TITLE
Reduce number of API calls

### ISSUE THREAD

**Issue by tm1000** [Weble/ZohoCrmApi#74]
A call of `$zohoCrm->locations->getList()` leads to three network requests each time this is called

- GET to /modules/locations
- GET to /modules
- GET to /locations

Couldn't the first two be cached? definitely the first one. Even if it was cached between php lifecycles would help immensely

**Comment by Skullbock** [comment]
Yeah this is something i wanted to check since a lot of time. I think we could "assume" that the module exists, and trigger then error if the module is not found upon call of `getList` reducing the number of calls to 1

**Comment by Skullbock** [comment]
In my latest push i fixed by simply not checking if the module exists, and let the getList throw an error if you try to do so
