### ISSUE TITLE
Check version 2.1 of the API

### ISSUE THREAD

**Issue by Skullbock** [Weble/ZohoCrmApi#81]
Zoho sent an email to every developer registered with the details of the new 2.1 release.
Check what's new and add the new stuff / changes to the library

https://xtpq.campaign-view.com/ua/viewinbrowser?od=3z468a38bc7069b8ed99bf23a2f891bc3f02959eb3a420a2e709ce726f0febc096&rd=117291c11e2753aa&sd=117291c11e274b49&n=11699e4bfb293d4&mrd=117291c11e274b37&m=1

@tm1000 Maybe you have already checked some of this?

**Comment by tm1000** [comment]
@Skullbock I haven't looked at this yet...

**Comment by Skullbock** [comment]
It's detectable in the sense that the base url of the apis is 2.1 instead of 2

We should decide if we support both or we just move to 2.1 following the breaking changes with a new major version. 

Classic wrong usage of sem ver by zoho btw
