### ISSUE TITLE
Version 5 Documentation

### ISSUE THREAD

**Issue by kaioken** [Weble/ZohoCrmApi#82]
Hey Guys, I've been using the package and saw you guys did a v5 release, but there is no doc around it, do you plan on updating the site?

Thanks

**Comment by Skullbock** [comment]
hi, we did indeed.
The docs should be mostly be unchanged. I think the only real change is the usage of the oauth client.
I will try to change the example to use this yes.
In the meantime, if you want to PR, the docs are on this repo too!

**Comment by kaioken** [comment]
@Skullbock thanks I'll take a look and let you know ;)
